### ISSUE TITLE
A simple question regarding slurm

### ISSUE THREAD

**Issue by itsOwen** [jamesgleave/DeepDockingGUI#11]
Hey there devs,

I recently tried setting up slurm on my local machine with munge authentication, setting up the config file as well. When I try to enter my username@password asked by the script it doesn't get connected not sure why. I know its some issue from my side but any help from the devs is appreciated.

Thanks.

**Comment by jyaacoub** [comment]
Could you give a bit more information perhaps some screenshots of errors (if any). Just make sure to blur any sensitive info like IP addrs.

Are you stuck during installation or when logging in through the browser?

**Comment by itsOwen** [comment]
I wanted to know that do i need to setup slurm on a remote computer? As I tried installing slurm on localhost with munge and installed all the required stuff.

When i try to do the cond setup step install locally, It asks for a ip and password, I am not sure if its slurm worker ip address or what password do I need to enter. The slurm bit is a little unclear to me. If there is a yt video or any deep documentation I would love to read it through.

I just want to figure out the slurm ip and pass part so It can install the rest of the stuff and I can start using it.

Dd_protocol manual is super good but I still have to go through a lot of commands, I mean I can do that easily but my colleagues need the gui version.

It would be great help, If you can help me with the slurm part.

Thanks for your time Jyaacoub.

**Comment by jyaacoub** [comment]
Interesting... We built the system to work as a sort of controller, sending commands to a separate SLURM cluster, but I could imagine if you set it up properly that it could also work within the same system.

However, I am not sure how exactly you would need to set it up (I don't know much about system engineering). Could you not SSH into that machine from a separate computer? There could be something going on with the commands being sent to the same system you are running and it interfacing with SLURM in a weird way.

Also just to clarify: what does the connection process to SLURM look like for you? do you connect using username@localip (e.g.: jyaacoub@127.0.0.1) followed by enter than your password?

This could also be an issue with the python library (paramiko) that is doing the connecting. Try connecting to the SLURM cluster first and see if that works using the following from the install.py file:
https://github.com/jamesgleave/DeepDockingGUI/blob/cdd947b794ae52db2bee124516c4455f2a7ef0b5/installation/install.py#L177

**Comment by itsOwen** [comment]
I will check this out thankyou very much :)
